Versionが所定のフォーマットに収まっているかをチェックするようにした。

diff --git a/.github/workflows/bump.yml b/.github/workflows/bump.yml
--- a/.github/workflows/bump.yml
+++ b/.github/workflows/bump.yml
@@ -29,7 +29,16 @@ jobs:
           ARM=$(curl -sL "https://github.com/kopi-vm/kopi/releases/download/v${LATEST}/kopi-${LATEST}-macos-aarch64.tar.gz.sha256")
           echo "arm_hash=${ARM}" >> "$GITHUB_OUTPUT"
 
+          if ! [[ "$LATEST" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "⚠️ Error: Version format must be x.x.x (e.g., 1.2.3)."
+            echo "valid=false" >> "$GITHUB_OUTPUT"
+          else
+            echo "✅ Version format is valid."
+            echo "valid=true" >> "$GITHUB_OUTPUT"
+          fi
+
       - name: Bump Formula
+        if: steps.metadata.outputs.valid == 'true'
         run: |
           cat > Formula/kopi.rb <<EOF
           class Kopi < Formula
@@ -76,11 +85,13 @@ jobs:
           end
 
       - name: Configure Git
+        if: steps.metadata.outputs.valid == 'true'
         run: |
           git config user.name "github-actions[bot]"
           git config user.email "github-actions[bot]@users.noreply.github.com"
 
       - name: Push Changes
+        if: steps.metadata.outputs.valid == 'true'
         run: |
           if ! git diff-index --quiet HEAD; then
             git add Formula/kopi.rb
